Imports System
Imports System.Collections.Generic
Imports System.Linq
Imports System.Text

Namespace RS
    Public NotInheritable Class Nations
        Inherits Dictionary(Of String, Nation)
        Public Shared ReadOnly UNKNOWN_NATION As New Nation("??", "??")
        Public Shared ReadOnly NO_NATION As New Nation("**", "**")

        Public Function getPhoneNumberNation(ByVal phone_number As String) As Nation
            If String.IsNullOrEmpty(phone_number) Then
                Return UNKNOWN_NATION
            End If
            For Each kvp As KeyValuePair(Of String, Nation) In Me
                If phone_number.StartsWith(kvp.Value.Prefix) Then
                    Return kvp.Value
                End If
            Next
            Return UNKNOWN_NATION
        End Function

        Public Shared ReadOnly ARUBA As New Nation("AW", "+297")
        Public Shared ReadOnly AFGHANISTAN As New Nation("AF", "+93")
        Public Shared ReadOnly ANGOLA As New Nation("AO", "+244")
        Public Shared ReadOnly ALBANIA As New Nation("AL", "+355")
        Public Shared ReadOnly ANDORRA As New Nation("AD", "+376")
        Public Shared ReadOnly NETHERLANDS_ANTILLES As New Nation("AN", "+599")
        Public Shared ReadOnly UNITED_ARAB_EMIRATES As New Nation("AE", "+971")
        Public Shared ReadOnly ARGENTINA As New Nation("AR", "+54")
        Public Shared ReadOnly ARMENIA As New Nation("AM", "+374")
        Public Shared ReadOnly AMERICAN_SAMOA As New Nation("AS", "+684")
        Public Shared ReadOnly AUSTRALIA As New Nation("AU", "+61")
        Public Shared ReadOnly AUSTRIA As New Nation("AT", "+43")
        Public Shared ReadOnly AZERBAIJAN As New Nation("AZ", "+994")
        Public Shared ReadOnly BURUNDI As New Nation("BI", "+257")
        Public Shared ReadOnly BELGIUM As New Nation("BE", "+32")
        Public Shared ReadOnly BENIN As New Nation("BJ", "+229")
        Public Shared ReadOnly BURKINA_FASO As New Nation("BF", "+226")
        Public Shared ReadOnly BANGLADESH As New Nation("BD", "+880")
        Public Shared ReadOnly BAHRAIN As New Nation("BH", "+973")
        Public Shared ReadOnly BOSNIA_AND_HERZEGOVINA As New Nation("BA", "+387")
        Public Shared ReadOnly BELARUS As New Nation("BY", "+375")
        Public Shared ReadOnly BELIZE As New Nation("BZ", "+501")
        Public Shared ReadOnly BOLIVIA As New Nation("BO", "+591")
        Public Shared ReadOnly BRAZIL As New Nation("BR", "+55")
        Public Shared ReadOnly BRUNEI_DARUSSALAM As New Nation("BN", "+673")
        Public Shared ReadOnly BHUTAN As New Nation("BT", "+975")
        Public Shared ReadOnly BOTSWANA As New Nation("BW", "+267")
        Public Shared ReadOnly CENTRAL_AFRICAN_REPUBLIC As New Nation("CF", "+236")
        Public Shared ReadOnly CHILE As New Nation("CL", "+56")
        Public Shared ReadOnly CHINA As New Nation("CN", "+86")
        Public Shared ReadOnly CAMEROON As New Nation("CM", "+237")
        Public Shared ReadOnly THE_DEMOCRATIC_REPUBLIC_OF_THE_CONGO As New Nation("CD", "+243")
        Public Shared ReadOnly CONGO As New Nation("CG", "+242")
        Public Shared ReadOnly COOK_ISLANDS As New Nation("CK", "+682")
        Public Shared ReadOnly COLOMBIA As New Nation("CO", "+57")
        Public Shared ReadOnly COMOROS As New Nation("KM", "+269")
        Public Shared ReadOnly CAPE_VERDE As New Nation("CV", "+238")
        Public Shared ReadOnly COSTA_RICA As New Nation("CR", "+506")
        Public Shared ReadOnly CUBA As New Nation("CU", "+53")
        Public Shared ReadOnly CYPRUS As New Nation("CY", "+357")
        Public Shared ReadOnly CZECH_REPUBLIC As New Nation("CZ", "+420")
        Public Shared ReadOnly DENMARK As New Nation("DK", "+45")
        Public Shared ReadOnly GERMANY As New Nation("DE", "+49")
        Public Shared ReadOnly DJIBOUTI As New Nation("DJ", "+253")
        Public Shared ReadOnly ALGERIA As New Nation("DZ", "+213")
        Public Shared ReadOnly ECUADOR As New Nation("EC", "+593")
        Public Shared ReadOnly ERITREA As New Nation("ER", "+291")
        Public Shared ReadOnly SPAIN As New Nation("ES", "+34")
        Public Shared ReadOnly ESTONIA As New Nation("EE", "+372")
        Public Shared ReadOnly ETHIOPIA As New Nation("ET", "+251")
        Public Shared ReadOnly FINLAND As New Nation("FI", "+358")
        Public Shared ReadOnly FIJI As New Nation("FJ", "+679")
        Public Shared ReadOnly FALKLAND_ISLANDS As New Nation("FK", "+500")
        Public Shared ReadOnly FRANCE As New Nation("FR", "+33")
        Public Shared ReadOnly FAROE_ISLANDS As New Nation("FO", "+298")
        Public Shared ReadOnly MICRONESIA As New Nation("FM", "+691")
        Public Shared ReadOnly GABON As New Nation("GA", "+241")
        Public Shared ReadOnly UNITED_KINGDOM As New Nation("GB", "+44")
        Public Shared ReadOnly GEORGIA As New Nation("GE", "+995")
        Public Shared ReadOnly GHANA As New Nation("GH", "+233")
        Public Shared ReadOnly GIBRALTAR As New Nation("GI", "+350")
        Public Shared ReadOnly GUINEA As New Nation("GN", "+224")
        Public Shared ReadOnly GAMBIA As New Nation("GM", "+220")
        Public Shared ReadOnly GUINEA_BISSAU As New Nation("GW", "+245")
        Public Shared ReadOnly EQUATORIAL_GUINEA As New Nation("GQ", "+240")
        Public Shared ReadOnly GREECE As New Nation("GR", "+30")
        Public Shared ReadOnly GREENLAND As New Nation("GL", "+299")
        Public Shared ReadOnly GUATEMALA As New Nation("GT", "+502")
        Public Shared ReadOnly FRENCH_GUIANA As New Nation("GF", "+594")
        Public Shared ReadOnly GUYANA As New Nation("GY", "+592")
        Public Shared ReadOnly HONG_KONG As New Nation("HK", "+852")
        Public Shared ReadOnly HONDURAS As New Nation("HN", "+504")
        Public Shared ReadOnly CROATIA As New Nation("HR", "+385")
        Public Shared ReadOnly HAITI As New Nation("HT", "+509")
        Public Shared ReadOnly HUNGARY As New Nation("HU", "+36")
        Public Shared ReadOnly INDIA As New Nation("IN", "+91")
        Public Shared ReadOnly IRELAND As New Nation("IE", "+353")
        Public Shared ReadOnly ISLAMIC_REPUBLIC_OF_IRAN As New Nation("IR", "+98")
        Public Shared ReadOnly IRAQ As New Nation("IQ", "+964")
        Public Shared ReadOnly ICELAND As New Nation("IS", "+354")
        Public Shared ReadOnly ISRAEL As New Nation("IL", "+972")
        Public Shared ReadOnly ITALY As New Nation("IT", "+39")
        Public Shared ReadOnly JORDAN As New Nation("JO", "+962")
        Public Shared ReadOnly JAPAN As New Nation("JP", "+81")
        Public Shared ReadOnly KENYA As New Nation("KE", "+254")
        Public Shared ReadOnly KYRGYZSTAN As New Nation("KG", "+996")
        Public Shared ReadOnly CAMBODIA As New Nation("KH", "+855")
        Public Shared ReadOnly KIRIBATI As New Nation("KI", "+686")
        Public Shared ReadOnly REPUBLIC_OF_KOREA As New Nation("KR", "+82")
        Public Shared ReadOnly KUWAIT As New Nation("KW", "+965")
        Public Shared ReadOnly LEBANON As New Nation("LB", "+961")
        Public Shared ReadOnly LIBERIA As New Nation("LR", "+231")
        Public Shared ReadOnly LIECHTENSTEIN As New Nation("LI", "+423")
        Public Shared ReadOnly SRI_LANKA As New Nation("LK", "+94")
        Public Shared ReadOnly LESOTHO As New Nation("LS", "+266")
        Public Shared ReadOnly LITHUANIA As New Nation("LT", "+370")
        Public Shared ReadOnly LUXEMBOURG As New Nation("LU", "+352")
        Public Shared ReadOnly LATVIA As New Nation("LV", "+371")
        Public Shared ReadOnly MACAO As New Nation("MO", "+853")
        Public Shared ReadOnly MOROCCO As New Nation("MA", "+212")
        Public Shared ReadOnly MONACO As New Nation("MC", "+377")
        Public Shared ReadOnly MOLDOVA As New Nation("MD", "+373")
        Public Shared ReadOnly MADAGASCAR As New Nation("MG", "+261")
        Public Shared ReadOnly MALDIVES As New Nation("MV", "+960")
        Public Shared ReadOnly MEXICO As New Nation("MX", "+52")
        Public Shared ReadOnly MARSHALL_ISLANDS As New Nation("MH", "+692")
        Public Shared ReadOnly THE_FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA As New Nation("MK", "+389")
        Public Shared ReadOnly MALI As New Nation("ML", "+223")
        Public Shared ReadOnly MALTA As New Nation("MT", "+356")
        Public Shared ReadOnly MYANMAR As New Nation("MM", "+95")
        Public Shared ReadOnly MONGOLIA As New Nation("MN", "+976")
        Public Shared ReadOnly MOZAMBIQUE As New Nation("MZ", "+258")
        Public Shared ReadOnly MAURITANIA As New Nation("MR", "+222")
        Public Shared ReadOnly MARTINIQUE As New Nation("MQ", "+596")
        Public Shared ReadOnly MAURITIUS As New Nation("MU", "+230")
        Public Shared ReadOnly MALAWI As New Nation("MW", "+265")
        Public Shared ReadOnly MAYOTTE As New Nation("YT", "+269")
        Public Shared ReadOnly NAMIBIA As New Nation("NA", "+264")
        Public Shared ReadOnly NEW_CALEDONIA As New Nation("NC", "+687")
        Public Shared ReadOnly NETHERLANDS As New Nation("NL", "+31")
        Public Shared ReadOnly NIGER As New Nation("NE", "+227")
        Public Shared ReadOnly NIGERIA As New Nation("NG", "+234")
        Public Shared ReadOnly NICARAGUA As New Nation("NI", "+505")
        Public Shared ReadOnly NIUE As New Nation("NU", "+683")
        Public Shared ReadOnly NORWAY As New Nation("NO", "+47")
        Public Shared ReadOnly NEPAL As New Nation("NP", "+977")
        Public Shared ReadOnly NAURU As New Nation("NR", "+674")
        Public Shared ReadOnly NEW_ZEALAND As New Nation("NZ", "+64")
        Public Shared ReadOnly OMAN As New Nation("OM", "+968")
        Public Shared ReadOnly PAKISTAN As New Nation("PK", "+92")
        Public Shared ReadOnly PANAMA As New Nation("PA", "+507")
        Public Shared ReadOnly PERU As New Nation("PE", "+51")
        Public Shared ReadOnly PHILIPPINES As New Nation("PH", "+63")
        Public Shared ReadOnly PALAU As New Nation("PW", "+680")
        Public Shared ReadOnly PAPUA_NEW_GUINEA As New Nation("PG", "+675")
        Public Shared ReadOnly POLAND As New Nation("PL", "+48")
        Public Shared ReadOnly PORTUGAL As New Nation("PT", "+351")
        Public Shared ReadOnly DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA As New Nation("KP", "+850")
        Public Shared ReadOnly PARAGUAY As New Nation("PY", "+595")
        Public Shared ReadOnly FRENCH_POLYNESIA As New Nation("PF", "+689")
        Public Shared ReadOnly QATAR As New Nation("QA", "+974")
        Public Shared ReadOnly REUNION As New Nation("RE", "+262")
        Public Shared ReadOnly ROMANIA As New Nation("RO", "+40")
        Public Shared ReadOnly RUSSIAN_FEDERATION As New Nation("RU", "+7")
        Public Shared ReadOnly RWANDA As New Nation("RW", "+250")
        Public Shared ReadOnly SAUDI_ARABIA As New Nation("SA", "+966")
        Public Shared ReadOnly SUDAN As New Nation("SD", "+249")
        Public Shared ReadOnly SENEGAL As New Nation("SN", "+221")
        Public Shared ReadOnly SINGAPORE As New Nation("SG", "+65")
        Public Shared ReadOnly SAINT_HELENA As New Nation("SH", "+290")
        Public Shared ReadOnly SOLOMON_ISLANDS As New Nation("SB", "+677")
        Public Shared ReadOnly SIERRA_LEONE As New Nation("SL", "+232")
        Public Shared ReadOnly SLOVENIA As New Nation("SI", "+386")
        Public Shared ReadOnly EL_SALVADOR As New Nation("SV", "+503")
        Public Shared ReadOnly SAN_MARINO As New Nation("SM", "+378")
        Public Shared ReadOnly SOMALIA As New Nation("SO", "+252")
        Public Shared ReadOnly SAINT_PIERRE_AND_MIQUELON As New Nation("PM", "+508")
        Public Shared ReadOnly SAO_TOME_AND_PRINCIPE As New Nation("ST", "+239")
        Public Shared ReadOnly SWITZERLAND As New Nation("CH", "+41")
        Public Shared ReadOnly SURINAME As New Nation("SR", "+597")
        Public Shared ReadOnly SLOVAKIA As New Nation("SK", "+421")
        Public Shared ReadOnly SWEDEN As New Nation("SE", "+46")
        Public Shared ReadOnly SWAZILAND As New Nation("SZ", "+268")
        Public Shared ReadOnly SEYCHELLES As New Nation("SC", "+248")
        Public Shared ReadOnly SYRIAN_ARAB_REPUBLIC As New Nation("SY", "+963")
        Public Shared ReadOnly CHAD As New Nation("TD", "+235")
        Public Shared ReadOnly TOGO As New Nation("TG", "+228")
        Public Shared ReadOnly THAILAND As New Nation("TH", "+66")
        Public Shared ReadOnly TAJIKISTAN As New Nation("TJ", "+992")
        Public Shared ReadOnly TOKELAU As New Nation("TK", "+690")
        Public Shared ReadOnly TURKMENISTAN As New Nation("TM", "+993")
        Public Shared ReadOnly TONGA As New Nation("TO", "+676")
        Public Shared ReadOnly TUNISIA As New Nation("TN", "+216")
        Public Shared ReadOnly TURKEY As New Nation("TR", "+90")
        Public Shared ReadOnly TUVALU As New Nation("TV", "+688")
        Public Shared ReadOnly TAIWAN As New Nation("TW", "+886")
        Public Shared ReadOnly TANZANIA As New Nation("TZ", "+255")
        Public Shared ReadOnly UGANDA As New Nation("UG", "+256")
        Public Shared ReadOnly UKRAINE As New Nation("UA", "+380")
        Public Shared ReadOnly URUGUAY As New Nation("UY", "+598")
        Public Shared ReadOnly UNITED_STATES As New Nation("US", "+1")
        Public Shared ReadOnly UZBEKISTAN As New Nation("UZ", "+998")
        Public Shared ReadOnly VENEZUELA As New Nation("VE", "+58")
        Public Shared ReadOnly VIET_NAM As New Nation("VN", "+84")
        Public Shared ReadOnly VANUATU As New Nation("VU", "+678")
        Public Shared ReadOnly WALLIS_AND_FUTUNA As New Nation("WF", "+681")
        Public Shared ReadOnly SAMOA As New Nation("WS", "+685")
        Public Shared ReadOnly YEMEN As New Nation("YE", "+967")
        Public Shared ReadOnly SOUTH_AFRICA As New Nation("ZA", "+27")
        Public Shared ReadOnly ZAMBIA As New Nation("ZM", "+260")
        Public Shared ReadOnly ZIMBABWE As New Nation("ZW", "+263")

        Private Sub New()
            Add("AW", ARUBA)
            Add("AF", AFGHANISTAN)
            Add("AO", ANGOLA)
            Add("AL", ALBANIA)
            Add("AD", ANDORRA)
            Add("AN", NETHERLANDS_ANTILLES)
            Add("AE", UNITED_ARAB_EMIRATES)
            Add("AR", ARGENTINA)
            Add("AM", ARMENIA)
            Add("AS", AMERICAN_SAMOA)
            Add("AU", AUSTRALIA)
            Add("AT", AUSTRIA)
            Add("AZ", AZERBAIJAN)
            Add("BI", BURUNDI)
            Add("BE", BELGIUM)
            Add("BJ", BENIN)
            Add("BF", BURKINA_FASO)
            Add("BD", BANGLADESH)
            Add("BH", BAHRAIN)
            Add("BA", BOSNIA_AND_HERZEGOVINA)
            Add("BY", BELARUS)
            Add("BZ", BELIZE)
            Add("BO", BOLIVIA)
            Add("BR", BRAZIL)
            Add("BN", BRUNEI_DARUSSALAM)
            Add("BT", BHUTAN)
            Add("BW", BOTSWANA)
            Add("CF", CENTRAL_AFRICAN_REPUBLIC)
            Add("CL", CHILE)
            Add("CN", CHINA)
            Add("CM", CAMEROON)
            Add("CD", THE_DEMOCRATIC_REPUBLIC_OF_THE_CONGO)
            Add("CG", CONGO)
            Add("CK", COOK_ISLANDS)
            Add("CO", COLOMBIA)
            Add("KM", COMOROS)
            Add("CV", CAPE_VERDE)
            Add("CR", COSTA_RICA)
            Add("CU", CUBA)
            Add("CY", CYPRUS)
            Add("CZ", CZECH_REPUBLIC)
            Add("DK", DENMARK)
            Add("DE", GERMANY)
            Add("DJ", DJIBOUTI)
            Add("DZ", ALGERIA)
            Add("EC", ECUADOR)
            Add("ER", ERITREA)
            Add("ES", SPAIN)
            Add("EE", ESTONIA)
            Add("ET", ETHIOPIA)
            Add("FI", FINLAND)
            Add("FJ", FIJI)
            Add("FK", FALKLAND_ISLANDS)
            Add("FR", FRANCE)
            Add("FO", FAROE_ISLANDS)
            Add("FM", MICRONESIA)
            Add("GA", GABON)
            Add("GB", UNITED_KINGDOM)
            Add("GE", GEORGIA)
            Add("GH", GHANA)
            Add("GI", GIBRALTAR)
            Add("GN", GUINEA)
            Add("GM", GAMBIA)
            Add("GW", GUINEA_BISSAU)
            Add("GQ", EQUATORIAL_GUINEA)
            Add("GR", GREECE)
            Add("GL", GREENLAND)
            Add("GT", GUATEMALA)
            Add("GF", FRENCH_GUIANA)
            Add("GY", GUYANA)
            Add("HK", HONG_KONG)
            Add("HN", HONDURAS)
            Add("HR", CROATIA)
            Add("HT", HAITI)
            Add("HU", HUNGARY)
            Add("IN", INDIA)
            Add("IE", IRELAND)
            Add("IR", ISLAMIC_REPUBLIC_OF_IRAN)
            Add("IQ", IRAQ)
            Add("IS", ICELAND)
            Add("IL", ISRAEL)
            Add("IT", ITALY)
            Add("JO", JORDAN)
            Add("JP", JAPAN)
            Add("KE", KENYA)
            Add("KG", KYRGYZSTAN)
            Add("KH", CAMBODIA)
            Add("KI", KIRIBATI)
            Add("KR", REPUBLIC_OF_KOREA)
            Add("KW", KUWAIT)
            Add("LB", LEBANON)
            Add("LR", LIBERIA)
            Add("LI", LIECHTENSTEIN)
            Add("LK", SRI_LANKA)
            Add("LS", LESOTHO)
            Add("LT", LITHUANIA)
            Add("LU", LUXEMBOURG)
            Add("LV", LATVIA)
            Add("MO", MACAO)
            Add("MA", MOROCCO)
            Add("MC", MONACO)
            Add("MD", MOLDOVA)
            Add("MG", MADAGASCAR)
            Add("MV", MALDIVES)
            Add("MX", MEXICO)
            Add("MH", MARSHALL_ISLANDS)
            Add("MK", THE_FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA)
            Add("ML", MALI)
            Add("MT", MALTA)
            Add("MM", MYANMAR)
            Add("MN", MONGOLIA)
            Add("MZ", MOZAMBIQUE)
            Add("MR", MAURITANIA)
            Add("MQ", MARTINIQUE)
            Add("MU", MAURITIUS)
            Add("MW", MALAWI)
            Add("YT", MAYOTTE)
            Add("NA", NAMIBIA)
            Add("NC", NEW_CALEDONIA)
            Add("NL", NETHERLANDS)
            Add("NE", NIGER)
            Add("NG", NIGERIA)
            Add("NI", NICARAGUA)
            Add("NU", NIUE)
            Add("NO", NORWAY)
            Add("NP", NEPAL)
            Add("NR", NAURU)
            Add("NZ", NEW_ZEALAND)
            Add("OM", OMAN)
            Add("PK", PAKISTAN)
            Add("PA", PANAMA)
            Add("PE", PERU)
            Add("PH", PHILIPPINES)
            Add("PW", PALAU)
            Add("PG", PAPUA_NEW_GUINEA)
            Add("PL", POLAND)
            Add("PT", PORTUGAL)
            Add("KP", DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA)
            Add("PY", PARAGUAY)
            Add("PF", FRENCH_POLYNESIA)
            Add("QA", QATAR)
            Add("RE", REUNION)
            Add("RO", ROMANIA)
            Add("RU", RUSSIAN_FEDERATION)
            Add("RW", RWANDA)
            Add("SA", SAUDI_ARABIA)
            Add("SD", SUDAN)
            Add("SN", SENEGAL)
            Add("SG", SINGAPORE)
            Add("SH", SAINT_HELENA)
            Add("SB", SOLOMON_ISLANDS)
            Add("SL", SIERRA_LEONE)
            Add("SI", SLOVENIA)
            Add("SV", EL_SALVADOR)
            Add("SM", SAN_MARINO)
            Add("SO", SOMALIA)
            Add("PM", SAINT_PIERRE_AND_MIQUELON)
            Add("ST", SAO_TOME_AND_PRINCIPE)
            Add("CH", SWITZERLAND)
            Add("SR", SURINAME)
            Add("SK", SLOVAKIA)
            Add("SE", SWEDEN)
            Add("SZ", SWAZILAND)
            Add("SC", SEYCHELLES)
            Add("SY", SYRIAN_ARAB_REPUBLIC)
            Add("TD", CHAD)
            Add("TG", TOGO)
            Add("TH", THAILAND)
            Add("TJ", TAJIKISTAN)
            Add("TK", TOKELAU)
            Add("TM", TURKMENISTAN)
            Add("TO", TONGA)
            Add("TN", TUNISIA)
            Add("TR", TURKEY)
            Add("TV", TUVALU)
            Add("TW", TAIWAN)
            Add("TZ", TANZANIA)
            Add("UG", UGANDA)
            Add("UA", UKRAINE)
            Add("UY", URUGUAY)
            Add("US", UNITED_STATES)
            Add("UZ", UZBEKISTAN)
            Add("VE", VENEZUELA)
            Add("VN", VIET_NAM)
            Add("VU", VANUATU)
            Add("WF", WALLIS_AND_FUTUNA)
            Add("WS", SAMOA)
            Add("YE", YEMEN)
            Add("ZA", SOUTH_AFRICA)
            Add("ZM", ZAMBIA)
            Add("ZW", ZIMBABWE)
            Add("??", UNKNOWN_NATION)
            Add("**", NO_NATION)
        End Sub

        Private Shared _instance As New Nations()
        Public Shared ReadOnly Property I() As Nations
            Get
                Return _instance
            End Get
        End Property

    End Class
End Namespace
